# Generated by Django 3.0.3 on 2023-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='identifier',
            field=models.CharField(default='', max_length=8, verbose_name='标识符'),
        ),
        migrations.AddField(
            model_name='subjectiveanswer',
            name='identifier',
            field=models.CharField(default='', max_length=8, verbose_name='标识符'),
        ),
    ]
